version: '3'
services:
  sql-server-2019-container:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: sql-server-2019-container-1
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Phu@123456789"
    ports:
      - "1435:1433"
    networks:
      - backend



  arthubbecloud:
    image: sewnguyenp2206/arthubbecloud:latest
    container_name:  arthubbecloud
    ports:
      - "8761:8761"
    networks:
      - backend


networks:
  backend:
